# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
  
script:  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("DriftDiffusionPoissonSystems"); Pkg.test("DriftDiffusionPoissonSystems"; coverage=true)'
